command:
  - "python"
  - "dash_app.py"

env:
  - name: USE_MOCK_BACKEND
    value: "false"
  - name: DATABRICKS_CATALOG
    value: "nef_catalog"
  - name: DATABRICKS_SCHEMA
    value: "neverending"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "beb00aeaaa803c3e"
